automated test on enforcing https
opendatakit/sync-endpoint-default-setup pull request #46
Opened 2022-07-19 14:47 UTC by jesse5555

created automated test for verification of the correct creation and setup of https.env file when the user opts to enforce-https

2022-07-19 16:07 UTC, jesse5555 commented on test/test_https.py
> +    result = runner.invoke(jw.app, input="odk-x\n\n\njesse@odk-x.com\n\n")
@matt9j @wbrunette
is there a way we can pass a an escape sequence for `Control` + `C`?
I really don't what to set up any certificates while running my tests.

2022-07-19 16:22 UTC, jesse5555 commented on test/test_https.py
> +    result = runner.invoke(jw.app, input="odk-x\n\n\njesse@odk-x.com\n\n")
i will enable pytest execution in our workflow after i am well convict that the testing logic works perfectly.

2022-07-22 08:20 UTC, matt9j requested changes
Hi Jesse,
This is a good start! Reviewing the code I understand now what the big challenge is with only running a part of the script in testing. If you wanted to stick with this approach, I think you can get around this by mocking the heavy setup_*_certificates functions and by creating a simplified typer app instance as part of the test that only has one command (with invoke_without_command set so it runs immediately) that is a function with no parameters wrapping `run_cache_setup(envParam=env)`

I think the approach of refactoring the code a bit to better isolate the function that we discussed on the call would also work!

2022-07-22 08:20 UTC, matt9j commented on init-odkx-sync-endpoint.py
> +    return (typer.confirm("enforce https?", default=True))
I don't think you need the extra parenthesis here.

2022-07-22 08:20 UTC, matt9j commented on test/test_https.py
> +import serial
The serial import is unused if you get rid of the ser variable, which is also unused.

2022-07-22 08:20 UTC, matt9j commented on test/test_https.py
> +ser = serial.Serial()
Unused variable

2022-07-22 08:20 UTC, matt9j commented on test/test_https.py
> +from distutils.command.install import install
Also unused in current code I think?

2022-07-22 08:20 UTC, matt9j commented on test/test_https.py
> +    os._exit(0)
I don't think you need an explicit call to os._exit here, since you want the overall process to continue to run if you have multiple test cases. Pytest should be responsible for running each test case and collecting the overall results.

2022-07-22 08:20 UTC, matt9j commented on test/test_https.py
> +    result = runner.invoke(jw.app, input="odk-x\n\n\njesse@odk-x.com\n\n")
Hi Jesse, I think to test the run_cache_setup function we're going to need to better isolate it. I have done some searching and don't think there is an easy way to pass C^C("control C"/the interrupt signal) in the way you would like.

We can get the same behavior though by creating a new app instance as part of the test that only has the one command in it, and then making sure we bind the "env" variable to the command function so that it doesn't take any parameters. That way we don't have to serialize the env variable into a command line argument and parse it again.

The most direct way to do this is to use `functools.partial`, but you can also do it explicitly by creating a new function that just calls jw.run_cache_setup(env) without taking any parameters itself. Once you have a parameterless function, you can then invoke it in the app directly to generate the prompts.

2022-07-22 08:20 UTC, matt9j commented on test/test_https.py
> +    mocker.patch('init-odkx-sync-endpoint.is_enforce_https', return_value=True)
You will also probably need to mock the heavy `init-odkx-sync-endpoint.setup_certbot_certificate` and `init-odkx-sync-endpoint.setup_manual_certificate` functions too to allow the test to run quickly. We don't want to actually have the test allocate real certificates in automation. There is actually a ratelimit that we will hit with certbot!

2022-07-22 08:20 UTC, matt9j commented on init-odkx-sync-endpoint.py
> +@app.command()
I don't think we want run_cache_setup to be a CLI command in the real script (here), only in the test. The real user shouldn't be able to invoke it directly.

2022-07-22 08:20 UTC, matt9j commented on init-odkx-sync-endpoint.py
> +
extra whitespace change

2022-07-22 08:24 UTC, matt9j reviewed
Attempting to change to a neutral comment vs. change request since this is just a work-in-progress, but unfortunately it looks like the "requested changes" history still shows : /

2022-08-05 05:23 UTC, jesse5555 commented
hey @matt9j @wbrunette I think this is ready and i kindly request for a review

2022-08-08 18:55 UTC, matt9j approved these changes
This PR looks good to me!

2022-08-08 18:57 UTC, matt9j approved these changes
This PR looks good to me!

2022-08-09 22:07 UTC, merged