Integrate internalisation in setup script
opendatakit/sync-endpoint-default-setup pull request #47
Opened 2022-07-31 17:35 UTC by jesse5555

gettext gives us the ability to embrace python's internalisation by
creating POT files and setting translatable strings in out setup-script.

2022-07-31 18:22 UTC, jesse5555 reviewed
Hey  @matt9j @wbrunette!

This has not yet worked.  compiling the script to generate  `.po` files is producing errors for now 
```
WARNING: Problem on line 197: '"""'
WARNING: Start of line didn't match any expected keyword.
WARNING: Problem on line 198: 'with open(filepath, mode="w") as f:'
WARNING: Start of line didn't match any expected keyword.
WARNING: Problem on line 199: 'for (key, val) in env.items():'
WARNING: Start of line didn't match any expected keyword.
WARNING: Problem on line 200: 'f.write("{}={}\\n".format(key, val))'
WARNING: Start of line didn't match any expected keyword.
WARNING: Problem on line 203: 'def parse_env_file(filepath: str) -> Dict[str, str]:'
WARNING: Start of line didn't match any expected keyword.
```

2022-07-31 18:22 UTC, jesse5555 commented on init-odkx-sync-endpoint.py
> +        typer.echo(_("Found configuration at {env_file_location}").format(env_file_location=env_file_location))
hey @matt9j @wbrunette, I landed on some resource https://www.mattlayman.com/blog/2015/i18n/ that opened my eyes alittle about how all this might work.

However, i am not sure if `_("some string {value}").formart(value=some-value)` is a right way to setup a transferable string.

2022-07-31 18:22 UTC, jesse5555 commented on locale/en/LC_MESSAGES/messages.po
> +msgid ""
i am using babel to generate these files but there is no way i can generate these translatable strings with the command `pybabel compile -i init-odkx-sync-endpoint.py -l en -d locale`

2022-08-09 22:51 UTC, matt9j commented on locale/en/LC_MESSAGES/messages.po
> +msgid ""
I think that you need to be using the "extract" command to generate the .po file first, then once you have a .po file, you "compile" it to a .mo file! Try the command `pybabel extract -o locale/en/LC_MESSAGES/messages.po ./` instead, and I think it should work on your machine to fill the .po file.

2022-08-11 21:48 UTC, jesse5555 commented on locale/en/LC_MESSAGES/messages.po
> +msgid ""
this actually worked @matt9j 
Thank you so much

2022-08-17 15:53 UTC, matt9j requested changes
Generally looks good! A couple small changes needed (see review) but the overall contribution structure is good!

2022-08-17 15:53 UTC, matt9j commented on init-odkx-sync-endpoint.py
> +translate = gettext.translation('handroll', localedir, fallback=True)
I think it would be better if the translation domain had some meaning to the project, maybe something like "odk-x-sync-endpoint-init" or something like that. It looks like "handroll" comes from an example.

2022-08-17 15:53 UTC, matt9j commented on init-odkx-sync-endpoint.py
> +        typer.echo(_("Found configuration at {env_file_location}").format(env_file_location=env_file_location))
I think this is a reasonable approach for now! The string will appear in the .po file as "some string {value}" and the translation will just need to keep the value format parameter intact.

2022-08-17 15:53 UTC, matt9j commented on init-odkx-sync-endpoint.py
> -    env:Dict[str, str] = envParam
Unrelated change in the commit. Okay for now, but in general it's better to try and keep each commit isolated to one specific set of changes.

2022-08-17 15:53 UTC, matt9j commented on init-odkx-sync-endpoint.py
> -    enforce_https = is_enforce_https()
I think you want to keep is_enforce_https() a separate function to allow mocking it during testing, right?

2022-08-17 15:53 UTC, matt9j commented on init-odkx-sync-endpoint.py
> +    typer.echo(_("Enforcing https: {enforce_https}"))
Missing the call to .format() here

2022-08-17 15:55 UTC, matt9j commented
Also a minor note, it's "internationalization", not "internalization"-- It's the same root as "international", like between nations. Internalization means the process of making something internal/inside, but we want to make the code international instead : )

2022-08-19 21:39 UTC, jesse5555 commented
> Also a minor note, it's "internationalization", not "internalization"-- It's the same root as "international", like between nations. Internalization means the process of making something internal/inside, but we want to make the code international to work in many different countries. I know it's a mouthful to pronounce haha : )

sorry for the typo. i actually hadnt have realised it until you spotted it out.  Thanks @matt9j

2022-08-19 21:41 UTC, jesse5555 commented on tests/test_https.py
> +    jw.setup_translator('fr')
@jesse5555 this must be changing the inputs to French.  Kindly share @matt9j if you know what i might be missing here

2022-08-21 07:58 UTC, jesse5555 commented
hey @matt9j @wbrunette 
Every thing works perfect now.  

I kindly request you to have a look.

2022-08-22 19:46 UTC, matt9j approved these changes
Looks great to me!

2022-08-22 19:46 UTC, merged