User-configurable stack name in init-odkx-sync-endpoint.py
opendatakit/sync-endpoint-default-setup pull request #49
Opened 2023-02-19 11:45 UTC by Ndacyayisenga-droid

fixes (https://github.com/odk-x/tool-suite-X/issues/194)

@linl33 @elmps2018 @wbrunette

2023-02-21 14:10 UTC, e2themillions requested changes
When the small indentation/formatting issues are resolved, I think this looks good? 👍

2023-02-21 14:10 UTC, e2themillions commented on init-odkx-sync-endpoint.py
> +    domain, email, stack_name = parse_env_file(env_file_location)
This looks good to me, except I think there is an indentation problem? (if that is fixed, the number of modified lines will also be reduced)

2023-02-21 14:10 UTC, e2themillions commented on init-odkx-sync-endpoint.py
> +            print("Password set to: {}".format(default_ldap_pwd))
Trailing whitespace...

2023-02-21 14:10 UTC, e2themillions commented on init-odkx-sync-endpoint.py
> +    return True
I think there is the same indentation issue here??

2023-02-21 14:10 UTC, e2themillions commented on init-odkx-sync-endpoint.py
> +    deploy_stack(https)
Missing newline at end of file

2023-06-17 17:32 UTC, wbrunette requested changes

2023-06-17 17:32 UTC, wbrunette commented on init-odkx-sync-endpoint.py
> -    os.system("git clone -b master --single-branch --depth=1 https://github.com/odk-x/sync-endpoint ; \
why would we want to clone more than the single-branch for the automated build? Takes up more space and takes longer

2024-03-03 17:53 UTC, closed without merging