Fix/stack-name-added_continued
opendatakit/sync-endpoint-default-setup pull request #51
Opened 2023-10-21 13:17 UTC by MariaAngella

Hello,

I am trying to resolve the merge conflicts as per issue [194](https://github.com/odk-x/tool-suite-X/issues/194).
Steps done;
1. Forked repo and checked out from development branch 
2. Edited 2 files init-odkx-sync-endpoint.py and https.env with changes made by @adityaofficial10 

Please guide if I'm on the right track.

Thank you and regards,
Maria Angella

2023-10-21 16:05 UTC, wbrunette commented
The env variable is array that has all the variables in it.

2023-10-23 04:08 UTC, MariaAngella commented
@wbrunette kindly review changes made.

Thanks and regards,
Maria Angella

2023-10-23 14:24 UTC, wbrunette requested changes
I am not sure this will work. You should test your code. 

To just have the code be the text parsing part. I suggest.
If you comment out  these functions in main, the code will only run the interactive questioning. 
run_docker_builds()
    run_sync_endpoint_build()
    deploy_stack(https)

The other part is the "if enforce_https:" if you set that to false the script will not try to run code to get the certificate

2023-10-23 14:24 UTC, wbrunette commented on init-odkx-sync-endpoint.py
> +        env, domain, email = parse_env_file(env_file_location)
this call should only return on variable, so i am confused on why 3 variables.

2023-10-25 15:46 UTC, MariaAngella commented
@wbrunette Thank you for the advice.

2024-03-03 17:54 UTC, closed without merging